I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 240, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/screens.rpy", line 100, in script
    if not debug:
  File "game/screens.rpy", line 100, in <module>
    if not debug:
NameError: name 'debug' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 240, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/screens.rpy", line 100, in script
    if not debug:
  File "renpy/ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "renpy/python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/screens.rpy", line 100, in <module>
    if not debug:
NameError: name 'debug' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 7.5.3.22090809
候鸟 准正式版 0.99
Fri Jan  6 21:22:04 2023
