I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 16947, in script
    $ renpy.action(Preference("auto-forward", "enable"))
  File "game/script.rpy", line 16947, in <module>
    $ renpy.action(Preference("auto-forward", "enable"))
AttributeError: 'module' object has no attribute 'action'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 16947, in script
    $ renpy.action(Preference("auto-forward", "enable"))
  File "renpy/ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 16947, in <module>
    $ renpy.action(Preference("auto-forward", "enable"))
AttributeError: 'module' object has no attribute 'action'

Windows-10-10.0.19041 AMD64
Ren'Py 7.5.3.22090809
候鸟 完整试玩（CG仍缺失3张、BGM有6首免费素材等替换，但演出基本修完的）内测版 v0.4 Demo0.4
Fri Dec  2 21:37:06 2022
